(require 'auto-complete)
(require 'auto-complete-config)
(ac-config-default)
(global-auto-complete-mode t)
(setq ac-use-fuzzy t)
(setq ac-use-comphist t)
(setq ac-ignore-case nil)
(setq ac-auto-show-menu 0.05)
(setq ac-quick-help-delay 0.5)
